### ISSUE TITLE
Python 3 does not have a csv.next() method

### ISSUE THREAD

**Issue by slink** [stanford-futuredata/ASAP#3]
the csv reader code appears to be broken [here](https://github.com/stanford-futuredata/ASAP/blob/24e95b2f76b213f1999b5f997beaa070519b1230/ASAP.py#L222) at ASAP.py#L222 because '_csv.reader' object has no attribute 'next' in Python 3. Instead the code on L222 should read `args._head = next(icsv)` for Python 3.

An easy fix is to either call sys.version_info to check for Python version, or at least include a note stating that this code depends on a Python 2 version of the csv package.

**Comment by kexinrong** [comment]
Thanks for the bringing up the issue and the suggested fix. We will give you an update once the issue gets resolved.

**Comment by kexinrong** [comment]
Pushed a fix in the [latest commit] (https://github.com/stanford-futuredata/ASAP/commit/b0a92aca68301cd513a40b3ff13b656446149cf1). Let me know if it doesn't work for you.
