### ISSUE TITLE
Inconsistent results from ASAP across application restarts

### ISSUE THREAD

**Issue by altunenes** [stanford-futuredata/ASAP#8]
I've encountered an issue with the ASAP (As-Sampled-As-Possible) smoothing algorithm implemented in JavaScript. The algorithm produces different results each time the application is restarted, despite being given the same input data. This inconsistency is not observed with other smoothing methods like Savitzky-Golay. :/ I also read your paper but what I understand is it should behave deterministic and source code https://github.com/stanford-futuredata/ASAP/blob/master/ASAP-optimized.js doesn't use some randomness.
any ideas?

## Steps to Reproduce
1. Initialize application with a fixed dataset
2. Apply ASAP smoothing to the dataset (by using [smooth ](https://github.com/stanford-futuredata/ASAP/blob/8b39db4bc92590cbe5b44ddace9b7bb1d677248b/ASAP-optimized.js#L239C1-L240C1))
3. Record the output
4. Close and restart the application
5. Repeat steps 2-3
6. Compare outputs from different runs

## Expected Behavior
The ASAP smoothing algorithm should produce consistent results given the same input data, regardless of application restarts.

Any ideas? I m just using it like that:

```typescript
const applySmoothing = useCallback((inputData: ReadonlyArray<number>, targetRes: number): number[] => {
  try {
    return smoothFunction(Array.from(inputData), targetRes);
  } catch (error) {
    console.error('Error in smoothing:', error);
    return Array.from(inputData);
  }
}, []);

const [dataSet1, dataSet2, label1, label2, metric, axisRange, pageCount] = useMemo(() => {
  const sourceData = useUnprocessedData && fullData ? fullData : processedData;
  let d1: number[], d2: number[] | null, l1: string, l2: string, m: number | null, range, total: number;

  // ... (switch case for different modes)

  if (useUnprocessedData && fullData) {
    // ... 
  } else {
    const targetRes = 100;
    d1 = applySmoothing(d1, targetRes);
    if (d2) d2 = applySmoothing(d2, targetRes);
    total = 1;
    setStartIndex(0);
    if (currentMode === "comparisonMode") {
      m = calculateCorrelation(sourceData.subject1.metric, sourceData.subject2.metric);
    } else {
      m = null;
    }
  }
  range = calculateAxisRange(d1, d2);
  return [d1, d2, l1, l2, m, range, total];
}, [processedData, fullData, useUnprocessedData, currentMode, currentPage, itemsPerPage, calculateAxisRange, applySmoothing]);
```

**Comment by altunenes** [comment]
my fault :-( 
I had my doubts whether this filter was detereministic or not, as there was some order confusion when loading the huge DB! I did very detailed tests and it passed them all! 

I'm still happy that these tests revealed problems in my main code haha.
cheers!!

**Comment by kexinrong** [comment]
Thanks for your interest and glad to hear that you resolved the problem. Have fun =)

**Comment by altunenes** [comment]
> Thanks for your interest and glad to hear that you resolved the problem. Have fun =)

Thank youuu! And for your contributions to making this complex thing as open source, it really helps a lot!!
